name: Tests

on:
  push:
    branches: [ "main" ]
  merge_group:
    types: [ "checks_requested" ]
  pull_request:

jobs:
  rust-checks:
    name: Rust Checks
    uses: ./.github/workflows/rust-checks.yml

  python-checks:
    name: Python Checks
    uses: ./.github/workflows/python-checks.yml

